"use client";

import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/router";
import Image from "next/image";
import Logo from "./logo.jpg";
import { useEffect } from 'react';

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  const [isOpen, setIsOpen] = useState(false);

  const toggleMenu = () => {
    setIsOpen(!isOpen);
  };

  const closeMenu = () => {
    setIsOpen(false);
  };


  return (
    <html lang="en">
      <body>
        <nav id="navbar" className="fixed w-full z-20 top-0 start-0 border-b border-gray-200 dark:border-gray-600">
          <div className="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">

            <Link href="/" className="flex items-center space-x-3 rtl:space-x-reverse">
              <Image src={Logo} width={60} height={70} />
              <span className="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">
                Purposeful Learning Partnership
              </span>
            </Link>

            {/* Hamburger button, visible on screens smaller than large */}
            <button
              onClick={toggleMenu}
              type="button"
              className="inline-flex items-center justify-center p-2 w-10 h-10 text-sm text-gray-500 rounded-lg hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600 xl:hidden"
              aria-controls="navbar-hamburger"
              aria-expanded={isOpen ? "true" : "false"}
            >
              <span className="sr-only">Open main menu</span>
              <svg
                className="w-5 h-5"
                aria-hidden="true"
                fill="none"
                viewBox="0 0 17 14"
              >
                <path
                  stroke="currentColor"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth="2"
                  d="M1 1h15M1 7h15M1 13h15"
                />
              </svg>
            </button>

            {/* Navbar links, shown on medium screens and larger */}
            <div className={`w-full xl:flex xl:w-auto ${isOpen ? "block" : "hidden"}`} id="navbar-hamburger">
              <ul className="flex flex-col font-medium mt-4 xl:mt-0 lg:flex-row lg:space-x-8">
                <li>
                  <Link href="/" onClick={closeMenu} className="block py-2 px-3 text-gray-900 rounded lg:bg-transparent lg:hover:bg-transparent md:border-0 hover:text-blue-700 lg:p-0 dark:text-white dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">
                    Home
                  </Link>
                </li>
                <li>
                  <Link href="/about" onClick={closeMenu} className="block py-2 px-3 text-gray-900 rounded lg:bg-transparent lg:hover:bg-transparent md:border-0 hover:text-blue-700 lg:p-0 dark:text-white dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">
                    About
                  </Link>
                </li>
                {/* <li>
                  <Link href="/events" onClick={closeMenu} className="block py-2 px-3 text-gray-900 rounded lg:bg-transparent lg:hover:bg-transparent md:border-0 hover:text-blue-700 lg:p-0 dark:text-white dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">
                    Events and Workshops
                  </Link>
                </li> */}
                <li>
                  <Link href="/programsandservices" onClick={closeMenu} className="block py-2 px-3 text-gray-900 rounded lg:bg-transparent lg:hover:bg-transparent md:border-0 hover:text-blue-700 lg:p-0 dark:text-white dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">
                    Programs and Services
                  </Link>
                </li>
                <li>
                  <Link href="/contact" onClick={closeMenu} className="block py-2 px-3 text-gray-900 rounded lg:bg-transparent lg:hover:bg-transparent md:border-0 hover:text-blue-700 lg:p-0 dark:text-white dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">
                    Contact
                  </Link>
                </li>
              </ul>
            </div>
          </div>
        </nav>

        <div>
          {children}
        </div>



        <footer class="bg-white dark:bg-gray-900">
          <div class="mx-auto w-full max-w-screen-xl p-4 py-6 lg:py-8">
            <div class="grid-row-2 grid-flow-col lg:flex lg:justify-between">
              <div class="mb-6 md:mb-0">
                <a href="https://flowbite.com/" class="flex items-center">
                  <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">&copy; Purposeful Learning Partnership</span>
                </a>
              </div>
              <div>
                <div className="grid grid-rows-3 grid-flow-col gap-4 place-content-start text-gray-500 dark:text-gray-400 font-medium mr-6 lg:pt-0 pt-4">
                  <div className="justify-self-end">
                    <a href="#" class="text-gray-500 hover:text-gray-900 dark:hover:text-white ">
                      <svg class="w-4 h-4 mt-1.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 8 19">
                        <path fill-rule="evenodd" d="M6.135 3H8V0H6.135a4.147 4.147 0 0 0-4.142 4.142V6H0v3h2v9.938h3V9h2.021l.592-3H5V3.591A.6.6 0 0 1 5.592 3h.543Z" clip-rule="evenodd" />
                      </svg>
                      <span class="sr-only">Email</span>
                    </a>
                  </div>

                  <div className="justify-self-end">
                    <a href="#" class="text-gray-500 hover:text-gray-900 dark:hover:text-white">
                      <svg class="w-4 h-4 mt-1.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 8 19">
                        <path fill-rule="evenodd" d="M6.135 3H8V0H6.135a4.147 4.147 0 0 0-4.142 4.142V6H0v3h2v9.938h3V9h2.021l.592-3H5V3.591A.6.6 0 0 1 5.592 3h.543Z" clip-rule="evenodd" />
                      </svg>
                      <span class="sr-only">Facebook page</span>
                    </a>
                  </div>

                  <div className="justify-self-end">
                    <a href="#" class="text-gray-500 hover:text-gray-900 dark:hover:text-white">
                      <svg class="w-4 h-4 mt-1.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 21 16">
                        <path d="M16.942 1.556a16.3 16.3 0 0 0-4.126-1.3 12.04 12.04 0 0 0-.529 1.1 15.175 15.175 0 0 0-4.573 0 11.585 11.585 0 0 0-.535-1.1 16.274 16.274 0 0 0-4.129 1.3A17.392 17.392 0 0 0 .182 13.218a15.785 15.785 0 0 0 4.963 2.521c.41-.564.773-1.16 1.084-1.785a10.63 10.63 0 0 1-1.706-.83c.143-.106.283-.217.418-.33a11.664 11.664 0 0 0 10.118 0c.137.113.277.224.418.33-.544.328-1.116.606-1.71.832a12.52 12.52 0 0 0 1.084 1.785 16.46 16.46 0 0 0 5.064-2.595 17.286 17.286 0 0 0-2.973-11.59ZM6.678 10.813a1.941 1.941 0 0 1-1.8-2.045 1.93 1.93 0 0 1 1.8-2.047 1.919 1.919 0 0 1 1.8 2.047 1.93 1.93 0 0 1-1.8 2.045Zm6.644 0a1.94 1.94 0 0 1-1.8-2.045 1.93 1.93 0 0 1 1.8-2.047 1.918 1.918 0 0 1 1.8 2.047 1.93 1.93 0 0 1-1.8 2.045Z" />
                      </svg>
                      <span class="sr-only">Instagram page</span>
                    </a>
                  </div>


                  <div className="text-gray-500 hover:text-gray-900 dark:hover:text-white">infor@purposefullearningpartnership.org</div>






                  <div className="text-gray-500 hover:text-gray-900 dark:hover:text-white">pusposefullearningpartnership</div>



                  <div className="text-gray-500 hover:text-gray-900 dark:hover:text-white">pusposefullearningpartnership</div>
                </div>

              </div>
            </div>
          </div>
          <hr class="my-6 border-gray-200 sm:mx-auto dark:border-gray-700 lg:my-8" />

        </footer>

      </body>
    </html >
  );
}
