"use client";

import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/router";
import Image from "next/image";
import Logo from "./logo.jpg";
import { useEffect } from 'react';

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  const [isOpen, setIsOpen] = useState(false);

  const toggleMenu = () => {
    setIsOpen(!isOpen);
  };

  const closeMenu = () => {
    setIsOpen(false);
  };


  return (
    <html lang="en">
      <body className="bg-gray-900">
        <nav id="navbar" className="fixed w-full z-20 top-0 start-0 border-b border-gray-600">
          <div className="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">

            <Link href="/" className="flex items-center space-x-3 rtl:space-x-reverse">
              <Image src={Logo} width={60} height={70} />
              <span className="self-center md:text-2xl sm:text-lg text-sm font-semibold whitespace-nowrap text-white">
                Purposeful Learning Partnership
              </span>
            </Link>

            {/* Hamburger button, visible on screens smaller than large */}
            <button
              onClick={toggleMenu}
              type="button"
              className="inline-flex items-center justify-center p-2 w-10 h-10 text-sm rounded-lg focus:outline-none focus:ring-2 text-gray-400 hover:bg-gray-700 focus:ring-gray-600 xl:hidden"
              aria-controls="navbar-hamburger"
              aria-expanded={isOpen ? "true" : "false"}
            >
              <span className="sr-only">Open main menu</span>
              <svg
                className="w-5 h-5"
                aria-hidden="true"
                fill="none"
                viewBox="0 0 17 14"
              >
                <path
                  stroke="currentColor"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth="2"
                  d="M1 1h15M1 7h15M1 13h15"
                />
              </svg>
            </button>

            {/* Navbar links, shown on medium screens and larger */}
            <div className={`w-full xl:flex xl:w-auto ${isOpen ? "block" : "hidden"}`} id="navbar-hamburger">
              <ul className="flex flex-col font-medium mt-4 xl:mt-0 lg:flex-row lg:space-x-8">
                <li>
                  <Link href="/" onClick={closeMenu} className="block py-2 px-3 text-gray-900 rounded lg:bg-transparent lg:hover:bg-transparent md:border-0 lg:p-0 text-white hover:text-blue-500 hover:bg-gray-700 hover:text-white md:hover:bg-transparent">
                    Home
                  </Link>
                </li>
                <li>
                  <Link href="/about" onClick={closeMenu} className="block py-2 px-3 text-gray-900 rounded lg:bg-transparent lg:hover:bg-transparent md:border-0 lg:p-0 text-white hover:text-blue-500 hover:bg-gray-700 hover:text-white md:hover:bg-transparent">
                    About
                  </Link>
                </li>
                {/* <li>
                  <Link href="/events" onClick={closeMenu} className="block py-2 px-3 text-gray-900 rounded lg:bg-transparent lg:hover:bg-transparent md:border-0 hover:text-blue-700 lg:p-0 dark:text-white dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">
                    Events and Workshops
                  </Link>
                </li> */}
                <li>
                  <Link href="/programsandservices" onClick={closeMenu} className="block py-2 px-3 text-gray-900 rounded lg:bg-transparent lg:hover:bg-transparent md:border-0 lg:p-0 text-white hover:text-blue-500 hover:bg-gray-700 hover:text-white md:hover:bg-transparent">
                    Programs and Services
                  </Link>
                </li>
                <li>
                  <Link href="/contact" onClick={closeMenu} className="block py-2 px-3 text-gray-900 rounded lg:bg-transparent lg:hover:bg-transparent md:border-0 lg:p-0 text-white hover:text-blue-500 hover:bg-gray-700 hover:text-white md:hover:bg-transparent">
                    Contact
                  </Link>
                </li>
              </ul>
            </div>
          </div>
        </nav>

        <div>
          {children}
        </div>



        <footer class="bg-gray-900">
          <div class="mx-auto w-full max-w-screen-xl p-4 py-6 lg:py-8">
            <div class="grid-row-2 grid-flow-col lg:flex lg:justify-between">
              <div class="mb-6 md:mb-0">
                <a href="https://flowbite.com/" class="flex items-center">
                  <span class="self-center md:text-2xl sm:text-lg xs:text-md font-semibold whitespace-nowrap text-white">&copy; Purposeful Learning Partnership</span>
                </a>
              </div>
              <div>
                <div className="grid grid-rows-4 grid-flow-col gap-4 place-content-start text-gray-500 dark:text-gray-400 font-medium mr-6 lg:pt-0 pt-4">
                  <div className="justify-self-end">
                    <a href="#" class="text-gray-500 hover:text-gray-900 dark:hover:text-white ">
                      <svg class="w-4 h-4 sm:mt-1.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor">
                        <path fill-rule="evenodd" d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1zm13 2.383-4.708 2.825L15 11.105zm-.034 6.876-5.64-3.471L8 9.583l-1.326-.795-5.64 3.47A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.741M1 11.105l4.708-2.897L1 5.383z" clip-rule="evenodd" />
                      </svg>
                      <span class="sr-only">Email</span>
                    </a>
                  </div>

                  <div className="justify-self-end">
                    <a href="#" class="text-gray-500 hover:text-gray-900 dark:hover:text-white ">
                      <svg class="w-4 h-4 sm:mt-1.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor">
                        <path fill-rule="evenodd" d="M3.654 1.328a.678.678 0 0 0-1.015-.063L1.605 2.3c-.483.484-.661 1.169-.45 1.77a17.6 17.6 0 0 0 4.168 6.608 17.6 17.6 0 0 0 6.608 4.168c.601.211 1.286.033 1.77-.45l1.034-1.034a.678.678 0 0 0-.063-1.015l-2.307-1.794a.68.68 0 0 0-.58-.122l-2.19.547a1.75 1.75 0 0 1-1.657-.459L5.482 8.062a1.75 1.75 0 0 1-.46-1.657l.548-2.19a.68.68 0 0 0-.122-.58zM1.884.511a1.745 1.745 0 0 1 2.612.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.68.68 0 0 0 .178.643l2.457 2.457a.68.68 0 0 0 .644.178l2.189-.547a1.75 1.75 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.6 18.6 0 0 1-7.01-4.42 18.6 18.6 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877z" clip-rule="evenodd" />
                      </svg>
                      <span class="sr-only">Phone</span>
                    </a>
                  </div>

                  <div className="justify-self-end">
                    <a href="https://www.facebook.com/profile.php?id=61560765306008" target="_blank" class="text-gray-500 hover:text-gray-900 dark:hover:text-white">
                      <svg class="w-4 h-4 sm:mt-1.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" >
                        <path fill-rule="evenodd" d="M6.135 3H8V0H6.135a4.147 4.147 0 0 0-4.142 4.142V6H0v3h2v9.938h3V9h2.021l.592-3H5V3.591A.6.6 0 0 1 5.592 3h.543Z" clip-rule="evenodd" />
                      </svg>
                      <span class="sr-only">Facebook page</span>
                    </a>
                  </div>

                  <div className="justify-self-end">
                    <a href= "https://www.instagram.com/purposefullearningpartnership?igsh=YzljYTk1ODg3Zg==" target="_blank" class="text-gray-500 hover:text-gray-900 dark:hover:text-white">
                      <svg class="w-4 h-4 sm:mt-1.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor">
                        <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.9 3.9 0 0 0-1.417.923A3.9 3.9 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.9 3.9 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.9 3.9 0 0 0-.923-1.417A3.9 3.9 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599s.453.546.598.92c.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.5 2.5 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.5 2.5 0 0 1-.92-.598 2.5 2.5 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233s.008-2.388.046-3.231c.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92s.546-.453.92-.598c.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92m-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217m0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334" />
                      </svg>
                      <span class="sr-only">Instagram page</span>
                    </a>
                  </div>


                  <div className="text-gray-500 md:text-xl sm:text-md text-xs hover:text-white">infor@purposefullearningpartnership.org</div>

                  <div className="text-gray-500 md:text-xl sm:text-md text-xs hover:text-white">0333-2234332</div>





                  <a href="https://www.facebook.com/profile.php?id=61560765306008" target="_blank" class="text-gray-500 hover:text-gray-900 dark:hover:text-white">
                  <div className="text-gray-500 md:text-xl sm:text-md text-xs hover:text-white">pusposefullearningpartnership</div>
                  </a>



                  <a href= "https://www.instagram.com/purposefullearningpartnership?igsh=YzljYTk1ODg3Zg==" target="_blank" class="text-gray-500 hover:text-gray-900 dark:hover:text-white">
                  <div className="text-gray-500 md:text-xl sm:text-md text-xs  hover:text-white">pusposefullearningpartnership</div>
                  </a>

                </div>

              </div>
            </div>
          </div>
          <hr class="my-6 border-gray-200 sm:mx-auto dark:border-gray-700 lg:my-8" />

        </footer>

      </body>
    </html >
  );
}
